version: '3'

services:
  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.client
    # stdlin_open: true
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client/src:/app/client/src

  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    command: ["nodemon","-L", "app.js"]
    volumes:
      - /app/server/node_modules
      - ./server:/app/server:rw


# volumes:
#   client-src: ./client/src
